PandaTea/Models/Menu.cs
/* Menu.cs
 * 
 * PROG3050: Programming Microsoft Enterprise Applications
 * Group 7
 * 
 * Revision History
 *          Ji Hong Ahn, 2019-09-12: Created
 *          Ji Hong Ahn, 2019-10-10: Renamed model classes
 *                                   Added documentation comments and header comments
 *                                   Removed unnecessary imports
 */
using System;
using System.Collections.Generic;

namespace PandaTea.Models
{
    /// <summary>
    /// Model class for Menu data
    /// </summary>
    public partial class Menu
    {
        public Menu()
        {
            Order = new HashSet<Order>();
        }

        public decimal MenuId { get; set; }
        public decimal ProductId { get; set; }
        public string Size { get; set; }
        public decimal? Price { get; set; }
        public int? Calories { get; set; }

        public Product Product { get; set; }
        public ICollection<Order> Order { get; set; }
    }
}

PandaTea/Controllers/MenusController.cs
/* MenusController.cs
 * 
 * PROG3050: Programming Microsoft Enterprise Applications
 * Group 7
 * 
 * Revision History
 *          Ji Hong Ahn, 2019-09-12: Created
 *          Ji Hong Ahn, 2019-10-10: Refined codes
 *                                   Added documentation comments and header comments
 * 
 */
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using PandaTea.Models;

namespace PandaTea.Controllers
{
    public class MenusController : Controller
    {
        private readonly PandaTeaContext _context;

        public MenusController(PandaTeaContext context)
        {
            _context = context;
        }

        /// <summary>
        /// Returns View for Index action
        /// </summary>
        /// <returns></returns>
        public async Task<IActionResult> Index()
        {
            string message = HttpContext.Session.GetString("FirstName") == null ?
                "" : "Welcome " + HttpContext.Session.GetString("FirstName") + "!";
            TempData["Message"] = message;
            ViewBag.Message = TempData["Message"];

            var pandaTeaContext = _context.Menu.Include(m => m.Product);
            return View(await pandaTeaContext.ToListAsync());
        }

        /// <summary>
        /// Check user selection against possiblemenu items
        /// </summary>
        /// <param name="menu">MenuModel data to validate</param>
        /// <returns>ActionResult with status and message</returns>
        public ActionResult CheckMenuItem(Menu menu)
        {
            var menuModel = _context.Menu.Where(s => s.ProductId == menu.ProductId && s.Size == menu.Size);
            var menuId = "";

            if (menuModel.Any())
            {
                foreach (var item in menuModel.ToList())
                {
                    menuId = item.MenuId.ToString();
                }

                HttpContext.Session.SetString("MenuId", menuId);
                HttpContext.Session.SetString("ProductId", (menu.ProductId).ToString());
                HttpContext.Session.SetString("Size", (menu.Size).ToString());
                if(menu.Size == "S")
                {
                    menu.Price = decimal.Parse("3.99");
                }
                else if (menu.Size == "M")
                {
                    menu.Price = decimal.Parse("4.49");
                }
                else if (menu.Size == "L")
                {
                    menu.Price = decimal.Parse("4.99");
                }
                else
                {
                    return Json(new { status = false, message = "Check menu item failed" });
                }

                HttpContext.Session.SetString("UnitPrice", (menu.Price).ToString());

                return Json(new { status = true, message = "Check menu item successful: " + menuId });
            }
            else
            {
                return Json(new { status = false, message = "Check menu item failed" });
            }

        }

        /// <summary>
        /// Returns View for Details action
        /// </summary>
        /// <param name="id">MenuId to select</param>
        /// <returns>View with Menu data</returns>
        public async Task<IActionResult> Details(decimal? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var menu = await _context.Menu
                .Include(m => m.Product)
                .FirstOrDefaultAsync(m => m.MenuId == id);
            if (menu == null)
            {
                return NotFound();
            }

            return View(menu);
        }

        /// <summary>
        /// Returns View for Create action
        /// </summary>
        /// <returns>View</returns>
        public IActionResult Create()
        {
            ViewData["ProductId"] = new SelectList(_context.Product, "ProductId", "ProductName");
            return View();
        }

        /// <summary>
        /// Inserts Menu data to the database
        /// </summary>
        /// <param name="menu">Menu data to insert</param>
        /// <returns>View with Menu data</returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("MenuId,ProductId,Size,Price,Calories")] Menu menu)
        {
            if (ModelState.IsValid)
            {
                _context.Add(menu);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["ProductId"] = new SelectList(_context.Product, "ProductId", "ProductName", menu.ProductId);
            return View(menu);
        }

        /// <summary>
        /// Returns View for Edit action
        /// </summary>
        /// <param name="id">MenuId to update/param>
        /// <returns>View with Menu data</returns>
        public async Task<IActionResult> Edit(decimal? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var menu = await _context.Menu.FindAsync(id);
            if (menu == null)
            {
                return NotFound();
            }
            ViewData["ProductId"] = new SelectList(_context.Product, "ProductId", "ProductName", menu.ProductId);
            return View(menu);
        }

        /// <summary>
        /// Updates Menu data with a MenuId to the database
        /// </summary>
        /// <param name="id">MenuId to update</param>
        /// <param name="menu">Menu data to update</param>
        /// <returns></returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(decimal id, [Bind("MenuId,ProductId,Size,Price,Calories")] Menu menu)
        {
            if (id != menu.MenuId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(menu);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!MenuExists(menu.MenuId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["ProductId"] = new SelectList(_context.Product, "ProductId", "ProductName", menu.ProductId);
            return View(menu);
        }

        /// <summary>
        /// Returns View for Delete action
        /// </summary>
        /// <param name="id">MenuId to delete</param>
        /// <returns>View with Menu data</returns>
        public async Task<IActionResult> Delete(decimal? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var menu = await _context.Menu
                .Include(m => m.Product)
                .FirstOrDefaultAsync(m => m.MenuId == id);
            if (menu == null)
            {
                return NotFound();
            }

            return View(menu);
        }

        /// <summary>
        /// Deletes Menu data with a given MenuId from the database
        /// </summary>
        /// <param name="id">MenuId to delete</param>
        /// <returns>IActionResult to return to Index action</returns>
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(decimal id)
        {
            var menu = await _context.Menu.FindAsync(id);
            _context.Menu.Remove(menu);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        /// <summary>
        /// Verifies if Menu data with the given OrderId exists
        /// </summary>
        /// <param name="id">MenuId to verify</param>
        /// <returns>true if a Menu exists</returns>
        private bool MenuExists(decimal id)
        {
            return _context.Menu.Any(e => e.MenuId == id);
        }
    }
}

PandaTea/Views/Menus/Create.cshtml
﻿@*
    Create.cshtml

    PROG3050: Programming Microsoft Enterprise Applications
    Group 7

    Revision History
             Haeryun Kwon, 2019-10-21: Modified


*@


@model PandaTea.Models.Menu


@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";

}

<h2>Create</h2>

<h4>Menu</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="ProductId" class="control-label"></label>
                <select asp-for="ProductId" class="form-control" asp-items="ViewBag.ProductId"></select>
            </div>
            <div class="form-group">
                <label asp-for="Size" class="control-label"></label>
                <input asp-for="Size" class="form-control" />
                <span asp-validation-for="Size" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Price" class="control-label"></label>
                <input asp-for="Price" class="form-control" />
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Calories" class="control-label"></label>
                <input asp-for="Calories" class="form-control" />
                <span asp-validation-for="Calories" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

PandaTea/Views/Menus/Delete.cshtml
﻿@*
    Delete.cshtml

    PROG3050: Programming Microsoft Enterprise Applications
    Group 7

    Revision History
             Haeryun Kwon, 2019-10-21: Modified

*@

@model PandaTea.Models.Menu


@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";

}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Menu</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
@Html.DisplayNameFor(model => model.Size)
</dt>
<dd>
@Html.DisplayFor(model => model.Size)
</dd>
<dt>
@Html.DisplayNameFor(model => model.Price)
</dt>
<dd>
@Html.DisplayFor(model => model.Price)
</dd>
<dt>
@Html.DisplayNameFor(model => model.Calories)
</dt>
<dd>
@Html.DisplayFor(model => model.Calories)
</dd>
<dt>
@Html.DisplayNameFor(model => model.Product)
</dt>
<dd>
@Html.DisplayFor(model => model.Product.ProductName)
</dd>
</dl>

<form asp-action="Delete">
    <input type="hidden" asp-for="MenuId" />
    <input type="submit" value="Delete" class="btn btn-default" /> |
    <a asp-action="Index">Back to List</a>
</form>
</div>

PandaTea/Views/Menus/Details.cshtml
﻿@*
    Details.cshtml

    PROG3050: Programming Microsoft Enterprise Applications
    Group 7

    Revision History
             Haeryun Kwon, 2019-10-27: Modified
             Samantha Dang, 2019-10-30: Bring user to Orders/Create 
             Samantha Dang, 2019-10-31: SaveOrder Ajax to save order data
             Haeryun kwon, 2019-11-21: Added Tempdata for authentication
*@

@model PandaTea.Models.Menu
@using Microsoft.AspNetCore.Http;

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
    TempData.Keep("Auth");

}

<div id="home-details-container">
    <div class="bbt-container">
        <div>
            <div class="bbt-name">
                @Html.DisplayFor(model => model.Product.ProductName)
            </div>
            <div class="bbt-price">
                @Html.DisplayFor(m => m.Price)
            </div>
            <div class="bbt-content">
                <div class="bbt-img">
                    <img src= "@Url.Content(Model.Product.ImagePath)" alt="Image" />
                </div>
                <div class="bbt-review">
                    <img src="~/images/star-filled.png" alt="star-filled" class="star-filled" />
                    <img src="~/images/star-filled.png" alt="star-filled" class="star-filled" />
                    <img src="~/images/star-filled.png" alt="star-filled" class="star-filled" />
                    <img src="~/images/star-filled.png" alt="star-filled" class="star-filled" />
                    <img src="~/images/star.png" alt="star" class="star" />
                </div>
            </div>
            <div class="bbt-details">
                <div class="size">
                    <input type="radio" name="size" value="S" checked="checked" /> Small (300 cals)<br>
                    <input type="radio" name="size" value="M" /> Medium (375 cals) + $0.50<br>
                    <input type="radio" name="size" value="L" /> Large (425 cals) + $0.50<br>
                </div>
                <div class="quantity">
                    <label>Quantity</label>
                    <input type="number" class="quantity-input" value="1" min="1" max="99" />
                </div>
            </div>
            <div>
                <button id="panda-btn" class="order-btn" onclick="SaveOrder()">Add to Order</button>
                <button id="panda-btn-2" class="cancel-btn">Cancel</button>
            </div>
        </div>
    </div>

    <div id="modal">
        <div class="modal-content">
            <div class="modal-heading">
                Added to your order
                <img src="~/images/close.png" alt="close-button" class="modal-close" />
            </div>
            <div class="modal-bbt-content">
                <div class="modal-bbt-img">
                    <img src="@Url.Content(Model.Product.ImagePath)" alt="Image" />
                </div>
                <div>
                    <div class="modal-bbt-name">
                        @Html.DisplayFor(model => model.Product.ProductName)
                    </div>
                    <div class="modal-bbt-details">
                        <div class="modal-size">
                            <label>Size:</label>
                            <div class="size-value"></div>
                        </div>
                        <div style="display: flex;">
                            <div class="modal-quantity">
                                <label>Qty: </label>
                                <div class="quantity-value"></div>
                            </div>
                            <div class="modal-price">
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div>
                <button id="panda-btn" class="back-btn">Back to Menu</button>
                <button id="panda-btn-3" class="confirm-order-btn" onclick="location.href='@Url.Action("Create", "Orders")'">Confirm Order</button>
            </div>
        </div>
    </div>
</div>


@section Scripts {
    <script>
        $(document).ready(function () {
            $(".confirm-order-btn").click(function () {
                var _url = '@Url.Action("Create", "Orders")';
                window.location.href = _url;
            });
            $(".order-btn").click(function () {
                $("#modal").css("display", "block");

                var quantity = $(".quantity-input").val();
                $(".quantity-value").text(quantity);

                var selectedSize = $("input:radio[name='size']:checked");
                if (selectedSize.length > 0) {
                    selectedValue = selectedSize.val();
                    $(".size-value").text(selectedValue);
                }

                var totalPrice = 0;
                if (selectedValue == "S") {
                    totalPrice = 3.99 * quantity;
                    $(".modal-price").text(totalPrice.toFixed(2));
                }
                if (selectedValue == "M") {
                    totalPrice = 4.49 * quantity;
                    $(".modal-price").text(totalPrice.toFixed(2));
                }
                if (selectedValue == "L") {
                    totalPrice = 4.99 * quantity;
                    $(".modal-price").text(totalPrice.toFixed(2));
                }
            });
            $(".cancel-btn").click(function () {
                var _url = '@Url.Action("Index", "Menus")';
                window.location.href = _url;
            });
            $(".back-btn").click(function () {
                var _url = '@Url.Action("Index", "Menus")';
                window.location.href = _url;
            });
            $(".modal-close").click(function () {
                $("#modal").css("display", "none");
            });
        }); 
        function SaveOrder() {
            $.ajax(
            {
                type: "POST",
                url:'@Url.Action("StoreQuantity", "Orders")',
                data: {
                    quantity: $(".quantity-input").val()
                },
                error: function (result) {
                    alert("Failed to add to order. Try Again!");
                },
                success: function (result) {
                    console.log(result);
                    if (result.status == true) {
                    }
                    else {
                        alert(result.message);
                    }
                }
            });
            $.ajax(
            {
                type: "POST",
                url: '@Url.Action("CheckMenuItem", "Menus")',
                data: {
                    size: $("input:radio[name='size']:checked").val(),
                    productId: "@Model.ProductId",
                },
                error: function (result) {
                    alert("Failed to add to order. Try Again!");
                },
                success: function (result) {
                    console.log(result);
                    if (result.status == true) {
                        $("#modal").css("display", "block");
                    }
                    else {
                        alert(result.message);
                    }
                }
            });
        };
        $('input:radio[name="size"]').change(function () {
            if ($(this).val() == 'S') {
                $(".bbt-price").text("3.99");
            }
            if ($(this).val() == 'M') {
                $(".bbt-price").text("4.49");
            }
            if ($(this).val() == 'L') {
                $(".bbt-price").text("4.99");
            }
        });
    </script>
}

PandaTea/Views/Menus/Edit.cshtml
﻿@*
    Edit.cshtml

    PROG3050: Programming Microsoft Enterprise Applications
    Group 7

    Revision History
             Haeryun Kwon, 2019-10-21: Modified

*@

@model PandaTea.Models.Menu


@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";

}

<h2>Edit</h2>

<h4>Menu</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="MenuId" />
            <div class="form-group">
                <label asp-for="ProductId" class="control-label"></label>
                <select asp-for="ProductId" class="form-control" asp-items="ViewBag.ProductId"></select>
                <span asp-validation-for="ProductId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Size" class="control-label"></label>
                <input asp-for="Size" class="form-control" />
                <span asp-validation-for="Size" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Price" class="control-label"></label>
                <input asp-for="Price" class="form-control" />
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Calories" class="control-label"></label>
                <input asp-for="Calories" class="form-control" />
                <span asp-validation-for="Calories" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

PandaTea/Views/Menus/Index.cshtml
﻿@*
    Index.cshtml

    PROG3050: Programming Microsoft Enterprise Applications
    Group 7

    Revision History
             Haeryun Kwon, 2019-10-21: Modified

*@

@model IEnumerable<PandaTea.Models.Menu>


@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
    TempData.Keep("Auth");

}

<div id="home-container">
    <div class="bbt-container">
        @foreach (var item in Model.GroupBy(x => x.ProductId).Select(y => y.First()).ToList())
        {
            <div class="bbt">
                <a asp-action="Details" asp-route-id="@item.MenuId">
                    <div>
                        <div class="bbt-img">
                            <div>
                                <img src= "@Url.Content(item.Product.ImagePath)" alt="Image" />
                             </div>
                        </div>
                        <div class="bbt-review">
                            <img src="~/images/star-filled.png" alt="star-filled" class="star-filled" />
                            <img src="~/images/star-filled.png" alt="star-filled" class="star-filled" />
                            <img src="~/images/star-filled.png" alt="star-filled" class="star-filled" />
                            <img src="~/images/star-filled.png" alt="star-filled" class="star-filled" />
                            <img src="~/images/star.png" alt="star" class="star" />
                        </div>
                    </div>
                    <div class="bbt-name">
                        @Html.DisplayFor(modelItem => item.Product.ProductName)
                    </div>
                </a>
            </div>
        }
    </div>
</div>